
import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Loader2 } from 'lucide-react';
import { chatWithContext } from '../services/api';
import { GraphData, ChatMessage } from '../types';

interface ChatPanelProps {
  graphData: GraphData;
}

/**
 * A lightweight renderer for basic markdown generated by Gemini.
 * Handles bolding (**text**), bullet points (* item), and line breaks.
 */
const FormattedMessage: React.FC<{ text: string }> = ({ text }) => {
  const lines = text.split('\n');
  
  return (
    <div className="space-y-2 text-sm leading-relaxed">
      {lines.map((line, lineIdx) => {
        if (!line.trim()) return <div key={lineIdx} className="h-2" />;

        // Handle bullet points
        const isBullet = line.trim().startsWith('* ') || line.trim().startsWith('- ');
        const cleanLine = isBullet ? line.trim().substring(2) : line;

        // Process bold markers (**text**)
        const parts = cleanLine.split(/(\*\*.*?\*\*)/g);
        const content = parts.map((part, partIdx) => {
          if (part.startsWith('**') && part.endsWith('**')) {
            return <strong key={partIdx} className="font-bold text-white">{part.slice(2, -2)}</strong>;
          }
          return part;
        });

        if (isBullet) {
          return (
            <div key={lineIdx} className="flex gap-2 pl-1">
              <span className="text-blue-400 font-bold">•</span>
              <span>{content}</span>
            </div>
          );
        }

        return <p key={lineIdx}>{content}</p>;
      })}
    </div>
  );
};

const ChatPanel: React.FC<ChatPanelProps> = ({ graphData }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: 'ai', content: 'Hi! I\'ve analyzed the story graph. Ask me anything about the characters or relationships!' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMsg = input.trim();
    setInput('');
    
    setMessages(prev => [...prev, { role: 'user', content: userMsg }]);
    setIsLoading(true);

    const sanitizeGraphForAI = (data: GraphData): any => {
      return {
        detected_language: data.detected_language,
        total_characters: data.total_characters,
        nodes: data.nodes.map(n => ({
          id: n.id,
          label_original: n.label_original,
          label_en: n.label_en,
          description_original: n.description_original,
          description_en: n.description_en,
          centrality: n.centrality,
        })),
        edges: data.edges.map(e => ({
          id: e.id,
          source: typeof e.source === 'object' ? (e.source as any).id : e.source,
          target: typeof e.target === 'object' ? (e.target as any).id : e.target,
          relation: {
            type_original: e.relation.type_original,
            type_en: e.relation.type_en,
            label_original: e.relation.label_original,
            label_en: e.relation.label_en,
          }
        }))
      };
    };

    try {
      const history = messages.map(m => ({ role: m.role, content: m.content }));
      const cleanContext = sanitizeGraphForAI(graphData);
      
      const response = await chatWithContext(userMsg, cleanContext, history);
      setMessages(prev => [...prev, { role: 'ai', content: response }]);
    } catch (error) {
      console.error('Chat Error:', error);
      setMessages(prev => [...prev, { role: 'ai', content: 'Sorry, I encountered an error processing the graph data for chat.' }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full bg-nodal-card border-l border-gray-700">
      {/* Header */}
      <div className="p-4 border-b border-gray-700 bg-nodal-dark/50 shadow-sm">
        <h3 className="text-lg font-semibold text-white flex items-center gap-2">
          <Bot className="text-blue-500" />
          Graph Assistant
        </h3>
        <p className="text-xs text-gray-400 mt-1">Analyzing character connections</p>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-6 custom-scrollbar">
        {messages.map((msg, idx) => (
          <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div 
              className={`max-w-[90%] rounded-2xl px-4 py-3 shadow-md ${
                msg.role === 'user' 
                  ? 'bg-blue-600 text-white rounded-br-none' 
                  : 'bg-gray-800 text-gray-100 rounded-bl-none border border-gray-700'
              }`}
            >
              {msg.role === 'user' ? (
                <p className="text-sm">{msg.content}</p>
              ) : (
                <FormattedMessage text={msg.content} />
              )}
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex justify-start">
             <div className="bg-gray-800 rounded-2xl rounded-bl-none px-4 py-3 flex items-center gap-3 border border-gray-700">
                <div className="flex gap-1">
                  <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                  <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                  <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce"></div>
                </div>
                <span className="text-xs text-gray-400 font-medium">Assistant is thinking...</span>
             </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-700 bg-nodal-dark/30">
        <div className="flex gap-2 relative">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Ask about character arcs or secrets..."
            className="flex-1 bg-gray-900 border border-gray-600 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 placeholder-gray-500 transition-all pr-12"
            disabled={isLoading}
          />
          <button
            onClick={handleSend}
            disabled={isLoading || !input.trim()}
            className="absolute right-1.5 top-1.5 bg-blue-600 hover:bg-blue-700 disabled:opacity-30 disabled:cursor-not-allowed text-white p-2 rounded-lg transition-all active:scale-95"
          >
            <Send size={18} />
          </button>
        </div>
        <p className="text-[10px] text-center text-gray-500 mt-2">Gemini 3 Flash Analysis</p>
      </div>
    </div>
  );
};

export default ChatPanel;
